config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
  resources :workshops do
    resources :workshop_registrations, except: :delete
    resources :bookings, except: :delete
    resources :ratings, except: [:new, :edit], controller: 'workshop_ratings'
    resources :images, only: [:create], controller: 'workshop_images'
    resources :workshop_sessions, only: [:create, :update, :destroy] do
      resources :comments, only: [:create]
      resources :participations, only: [:create]
    end
    get 'random', on: :collection
  end
  resources :categories, only: [:index, :show] do
    resources :workshops, only: [:index, :show]
  end
  resources :levels, only: [:index, :show]
  resources :users, except: [:index, :new, :edit, :create] do
    member do
      get :stripe_account_connect
    end
    resources :workshops, only: [:index], controller: 'user_workshops'
    resources :images, only: [:create], controller: 'user_images'
    resources :payment_methods, only: [:index, :destroy], controller: 'user_payment_methods'
  end

  post 'authenticate_with_facebook' => 'users#authenticate_with_facebook'
  get 'stripe_connect_callback' => 'stripe#connect_callback'
  get 'stripe_giropay_callback' => 'stripe#giropay_callback'
  post 'stripe_webhook' => 'stripe#event_webhook'
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :workshop_session
  has_one :workshop, through: :workshop_session
  belongs_to :user
  belongs_to :order

  validates :workshop_session, presence: true
  validates :user, presence: true
end

app/controllers/participations_controller.rb
class ParticipationsController < ApiController
  before_action :set_workshop_session
  before_action :authenticate_user!

  # POST /participations
  # POST /participations.json
  def create
    if @workshop_session.nil?
      return render json: {error: "Session not found"}, status: :not_found
    end

    allocatable =  (@workshop_session.workshop.maximum_workshop_registration_count || 999) - @workshop_session.participations.count

    if allocatable < 0
      return render json: {error: "Maximum registrations reached"}, status: :unprocessable_entity
    end

    if allocatable < requested_participation_count
      return render json: {error: "Only #{allocatable} tickets can be reserved"}, status: :unprocessable_entity
    end

    # create order object
    order = Order.create(payment_method: payment_method())
    if !order.save!
      return render json: order.errors, status: :unprocessable_entity
    else
      # create participations
      participations = []

      requested_participation_count.times {

        p = Participation.new(participation_params)
        # add participations to order object
        p.order = order

        if p.save!
          participations.append(p)
        else
          participations.map{ |pd| pd.delete }
          return render json: participation.errors, status: :unprocessable_entity
        end
      }
    end

    # trigger payment on order
    order.trigger_payment_transaction

    render json: participations, status: :created
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_participation
    @participation = Participation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def participation_params
    {}.merge(:user_id => current_user.id, workshop_session_id: workshop_session_id())
  end

  def set_workshop_session
    @workshop_session = WorkshopSession.includes(:workshop).find_by(id: workshop_session_id())
  end

  def requested_participation_count
    (params[:requested_participation_count] || 1).to_i
  end

  def payment_method
    params[:payment_method]
  end

  def workshop_id()
    params[:workshop_id]
  end

  def workshop_session_id()
    params[:workshop_session_id]
  end
end

app/views/participations/_form.html.haml
= form_for @participation do |f|
  - if @participation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@participation.errors.count, "error")} prohibited this participation from being saved:"
      %ul
        - @participation.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :workshop_session
    = f.text_field :workshop_session
  .field
    = f.label :workshop_registration
    = f.text_field :workshop_registration
  .field
    = f.label :score
    = f.text_field :score
  .actions
    = f.submit 'Save'

app/views/participations/edit.html.haml
%h1 Editing participation

= render 'form'

= link_to 'Show', @participation
\|
= link_to 'Back', participations_path

app/views/participations/index.html.haml
%h1 Listing participations

%table
  %thead
    %tr
      %th Workshop session
      %th WorkshopRegistration
      %th Score
      %th
      %th
      %th

  %tbody
    - @participations.each do |participation|
      %tr
        %td= participation.workshop_session
        %td= participation.workshop_registration
        %td= participation.score
        %td= link_to 'Show', participation
        %td= link_to 'Edit', edit_participation_path(participation)
        %td= link_to 'Destroy', participation, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Participation', new_participation_path

app/views/participations/new.html.haml
%h1 New participation

= render 'form'

= link_to 'Back', participations_path

app/views/participations/show.html.haml
%p#notice= notice

%p
  %b Workshop session:
  = @participation.workshop_session
%p
  %b WorkshopRegistration:
  = @participation.workshop_registration
%p
  %b Score:
  = @participation.score

= link_to 'Edit', edit_participation_path(@participation)
\|
= link_to 'Back', participations_path