config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
  resources :workshops do
    resources :workshop_registrations, except: :delete
    resources :bookings, except: :delete
    resources :ratings, except: [:new, :edit], controller: 'workshop_ratings'
    resources :images, only: [:create], controller: 'workshop_images'
    resources :workshop_sessions, only: [:create, :update, :destroy] do
      resources :comments, only: [:create]
      resources :participations, only: [:create]
    end
    get 'random', on: :collection
  end
  resources :categories, only: [:index, :show] do
    resources :workshops, only: [:index, :show]
  end
  resources :levels, only: [:index, :show]
  resources :users, except: [:index, :new, :edit, :create] do
    member do
      get :stripe_account_connect
    end
    resources :workshops, only: [:index], controller: 'user_workshops'
    resources :images, only: [:create], controller: 'user_images'
    resources :payment_methods, only: [:index, :destroy], controller: 'user_payment_methods'
  end

  post 'authenticate_with_facebook' => 'users#authenticate_with_facebook'
  get 'stripe_connect_callback' => 'stripe#connect_callback'
  get 'stripe_giropay_callback' => 'stripe#giropay_callback'
  post 'stripe_webhook' => 'stripe#event_webhook'
end

app/models/workshop_session.rb
class WorkshopSession < ApplicationRecord
  belongs_to :workshop
  has_many :participations
  has_many :participants, through: :participations, source: :user

  translates :title, :subtitle, :description

  validates :starts_at, presence: true
  validates :ends_at, {
    presence: true,
    date: {
      after: :starts_at,
      message: "A session cannot end before it starts"
    }
  }
  validates :ends_at, {
    presence: true,
    date: {
      before_or_equal_to: Proc.new { |obj| obj.starts_at.end_of_day },
      message: "A session should start and end on the same day"
    }
  }
end

app/controllers/workshop_sessions_controller.rb
class WorkshopSessionsController < ApiController
  before_action :set_workshop_session, only: [:update, :destroy]
  before_action :authenticate_user!

  def create
    @workshop_session = WorkshopSession.new(workshop_session_params)

    if @workshop_session.save
      render json: @workshop_session, status: :created
    else
      render json: @workshop_session.errors, status: :unprocessable_entity

    end
  end

  def update
    if @workshop_session.update(workshop_session_params)
      render json: nil, status: :no_content
    else
      render json: @workshop_session.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @workshop_session
      if @workshop_session.participations.count > 0
        return render json: {error: "Cannot delete: You have #{@workshop_session.participations.count} participants"}, status: :unprocessable_entity
      end
      @workshop_session.destroy
      render json: nil, status: :no_content
    else
      render json: {}, status: :not_found
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_workshop_session
    @workshop_session = WorkshopSession.find_by(id: params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def workshop_session_params
    params.require(:workshop_session).permit(:starts_at, :ends_at).merge(:workshop_id => workshop_id())
  end

  def workshop_id()
    params[:workshop_id]
  end
end

app/views/workshop_sessions/_form.html.haml
= form_for @workshop_session do |f|
  - if @workshop_session.errors.any?
    #error_explanation
      %h2= "#{pluralize(@workshop_session.errors.count, "error")} prohibited this workshop_session from being saved:"
      %ul
        - @workshop_session.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title_translations
    = f.text_field :title_translations
  .field
    = f.label :subtitle_translations
    = f.text_field :subtitle_translations
  .field
    = f.label :description_translations
    = f.text_field :description_translations
  .field
    = f.label :starts_at
    = f.datetime_select :starts_at
  .field
    = f.label :ends_at
    = f.datetime_select :ends_at
  .field
    = f.label :level
    = f.text_field :level
  .field
    = f.label :main_image
    = f.text_field :main_image
  .field
    = f.label :more_images
    = f.text_field :more_images
  .field
    = f.label :tutor
    = f.text_field :tutor
  .field
    = f.label :workshop
    = f.text_field :workshop
  .field
    = f.label :venue
    = f.text_field :venue
  .field
    = f.label :minimum_participation_count
    = f.number_field :minimum_participation_count
  .field
    = f.label :maximum_participation_count
    = f.number_field :maximum_participation_count
  .actions
    = f.submit 'Save'

app/views/workshop_sessions/_workshop_session.html.haml
%h1 Showing workshop sessions 

app/views/workshop_sessions/edit.html.haml
%h1 Editing workshop_session

= render 'form'

= link_to 'Show', @workshop_session
\|
= link_to 'Back', workshop_sessions_path

app/views/workshop_sessions/index.html.haml
%h1 Listing workshop_sessions

%table
  %thead
    %tr
      %th Title translations
      %th Subtitle translations
      %th Description translations
      %th Starts at
      %th Ends at
      %th Level
      %th Main image
      %th More images
      %th Tutor
      %th Workshop
      %th Venue
      %th Minimum participation count
      %th Maximum participation count
      %th
      %th
      %th

  %tbody
    - @workshop_sessions.each do |workshop_session|
      %tr
        %td= workshop_session.title_translations
        %td= workshop_session.subtitle_translations
        %td= workshop_session.description_translations
        %td= workshop_session.starts_at
        %td= workshop_session.ends_at
        %td= workshop_session.level
        %td= workshop_session.main_image
        %td= workshop_session.more_images
        %td= workshop_session.tutor
        %td= workshop_session.workshop
        %td= workshop_session.venue
        %td= workshop_session.minimum_participation_count
        %td= workshop_session.maximum_participation_count
        %td= link_to 'Show', workshop_session
        %td= link_to 'Edit', edit_workshop_session_path(workshop_session)
        %td= link_to 'Destroy', workshop_session, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Workshop session', new_workshop_session_path

app/views/workshop_sessions/new.html.haml
%h1 New workshop_session

= render 'form'

= link_to 'Back', workshop_sessions_path

app/views/workshop_sessions/show.html.haml
%p#notice= notice

%p
  %b Title translations:
  = @workshop_session.title_translations
%p
  %b Subtitle translations:
  = @workshop_session.subtitle_translations
%p
  %b Description translations:
  = @workshop_session.description_translations
%p
  %b Starts at:
  = @workshop_session.starts_at
%p
  %b Ends at:
  = @workshop_session.ends_at
%p
  %b Level:
  = @workshop_session.level
%p
  %b Main image:
  = @workshop_session.main_image
%p
  %b More images:
  = @workshop_session.more_images
%p
  %b Tutor:
  = @workshop_session.tutor
%p
  %b Workshop:
  = @workshop_session.workshop
%p
  %b Venue:
  = @workshop_session.venue
%p
  %b Minimum participation count:
  = @workshop_session.minimum_participation_count
%p
  %b Maximum participation count:
  = @workshop_session.maximum_participation_count

= link_to 'Edit', edit_workshop_session_path(@workshop_session)
\|
= link_to 'Back', workshop_sessions_path