config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]
  resources :workshops do
    resources :workshop_registrations, except: :delete
    resources :bookings, except: :delete
    resources :ratings, except: [:new, :edit], controller: 'workshop_ratings'
    resources :images, only: [:create], controller: 'workshop_images'
    resources :workshop_sessions, only: [:create, :update, :destroy] do
      resources :comments, only: [:create]
      resources :participations, only: [:create]
    end
    get 'random', on: :collection
  end
  resources :categories, only: [:index, :show] do
    resources :workshops, only: [:index, :show]
  end
  resources :levels, only: [:index, :show]
  resources :users, except: [:index, :new, :edit, :create] do
    member do
      get :stripe_account_connect
    end
    resources :workshops, only: [:index], controller: 'user_workshops'
    resources :images, only: [:create], controller: 'user_images'
    resources :payment_methods, only: [:index, :destroy], controller: 'user_payment_methods'
  end

  post 'authenticate_with_facebook' => 'users#authenticate_with_facebook'
  get 'stripe_connect_callback' => 'stripe#connect_callback'
  get 'stripe_giropay_callback' => 'stripe#giropay_callback'
  post 'stripe_webhook' => 'stripe#event_webhook'
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :workshop_sessions
  has_many :workshops

  translates :name

  validates :value, inclusion: 0..100
  validates :name_en, length: { within: 2..64 }
  validates :name_de, length: { within: 2..64 }
end

app/controllers/levels_controller.rb
class LevelsController < ApiController
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_params
      params.require(:level).permit(:name_translations, :value, :is_active)
    end
end

app/views/levels/_form.html.haml
= form_for @level do |f|
  - if @level.errors.any?
    #error_explanation
      %h2= "#{pluralize(@level.errors.count, "error")} prohibited this level from being saved:"
      %ul
        - @level.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name_translations
    = f.text_field :name_translations
  .field
    = f.label :value
    = f.number_field :value
  .field
    = f.label :is_active
    = f.check_box :is_active
  .actions
    = f.submit 'Save'

app/views/levels/edit.html.haml
%h1 Editing level

= render 'form'

= link_to 'Show', @level
\|
= link_to 'Back', levels_path

app/views/levels/index.html.haml
%h1 Listing levels

%table
  %thead
    %tr
      %th Name translations
      %th Value
      %th Is active
      %th
      %th
      %th

  %tbody
    - @levels.each do |level|
      %tr
        %td= level.name_translations
        %td= level.value
        %td= level.is_active
        %td= link_to 'Show', level
        %td= link_to 'Edit', edit_level_path(level)
        %td= link_to 'Destroy', level, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Level', new_level_path

app/views/levels/new.html.haml
%h1 New level

= render 'form'

= link_to 'Back', levels_path

app/views/levels/show.html.haml
%p#notice= notice

%p
  %b Name translations:
  = @level.name_translations
%p
  %b Value:
  = @level.value
%p
  %b Is active:
  = @level.is_active

= link_to 'Edit', edit_level_path(@level)
\|
= link_to 'Back', levels_path